sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - XDEBUG_MODE=coverage

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 8.0

notifications:
  email: false

before_install:
  - composer self-update
  - chmod -R +rwX test/asset/data

install:
  - travis_retry composer install
  - composer show --installed

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs

after_script:
  - php vendor/bin/coveralls
