sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - XDEBUG_MODE=coverage

php:
  - 7.4
  - 8.0

notifications:
  email: false

before_install:
  - composer self-update
  - chmod -R +rwX test/asset/data

install:
  - |
    if [ $(phpenv version-name) != '8.0' ]; then
      travis_retry composer install --prefer-source --no-interaction
    fi
    if [ $(phpenv version-name) == '8.0' ]; then
      travis_retry composer install --prefer-source --no-interaction --ignore-platform-req=php
    fi
  - composer show --installed

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs

after_script:
  - php vendor/bin/coveralls
